curl -XDELETE 10.0.0.114:9200/companyinfo
curl -XPUT 10.0.0.114:9200/companyinfo -d '
{
 "mappings" : {
  "_default_" : {
   "properties" : {	
	"Year":{"type": "string", "index" : "not_analyzed" },
	"stockId":{"type": "string", "index" : "not_analyzed" },
	"CurrentRatioX":{ "type" : "float" },
	"QuickRatioX":{ "type" : "float" },
	"LongTermDebtEquity":{ "type" : "float" },
	"TotalDebtEquity":{ "type" : "float" },
	"TotalDebtCapitalEmployed":{ "type" : "float" },
	"ReturnonEquity":{ "type" : "float" },
	"ReturnonCapitalEmploy":{ "type" : "float" },
	"ReturnonTotalAssets":{ "type" : "float" },
	"OperatingProfitMargin":{ "type" : "float" },
	"Pre-taxProfitMargin":{ "type" : "float" },
	"NetProfitMargin":{ "type" : "float" },
	"InventoryTurnoverX":{ "type" : "float" },
	"DividendPayout":{ "type" : "float" },
	"FiscalYearHigh":{ "type" : "float" },
	"FiscalYearLow":{ "type" : "float" },
	"FiscalYearPERRangeHighX":{ "type" : "float" },
	"FiscalYearPERRangeLowX":{ "type" : "float" },
	"FiscalYearYieldRangeHigh":{ "type" : "float" },
	"FiscalYearYieldRangeLow":{ "type" : "float" },
	"Turnover":{ "type" : "float" },
	"OperatingProfit":{ "type" : "float" },
	"ExceptionalItems":{ "type" : "float" },
	"Associates":{ "type" : "float" },
	"OtherNon-OperatingGainsLosses":{ "type" : "float" },
	"ProfitBeforeTaxation":{ "type" : "float" },
	"Taxation":{ "type" : "float" },
	"MinorityInterests":{ "type" : "float" },
	"NetProfit":{ "type" : "float" },
	"Currency":{"type": "string"},
	"Unit":{"type": "string"},
	"Depreciation":{ "type" : "float" },
	"InterestPaid":{ "type" : "float" },
	"InterestCapitalized":{ "type" : "float" },
	"Non-currentAssetsRevaluationDisposal":{ "type" : "float" },
	"TaxationRate":{ "type" : "float" },
	"TurnoverGrowth":{ "type" : "float" },
	"NetProfitGrowth":{ "type" : "float" },
	"AuditorsOpinion":{ "type" : "float" },
	"NetCashFlowfromOperatingActivities":{ "type" : "float" },
	"NetCashFlowfromReturnonInvestments&ServicingofFinance":{ "type" : "float" },
	"InterestReceived":{ "type" : "float" },
	"InterestPaid":{ "type" : "float" },
	"DividendReceived":{ "type" : "float" },
	"DividendPaid":{ "type" : "float" },
	"Others":{ "type" : "float" },
	"TaxesPaidRefunded":{ "type" : "float" },
	"NetCashFlowfromInvestingActivities":{ "type" : "float" },
	"AdditionstoFixedAssets":{ "type" : "float" },
	"DisposalofFixedAssets":{ "type" : "float" },
	"IncreaseinInvestments":{ "type" : "float" },
	"DecreaseinInvestments":{ "type" : "float" },
	"NetCashFlowwithRelatedParties":{ "type" : "float" },
	"NetCashFlowbeforeFinancingActivities":{ "type" : "float" },
	"NetCashFlowfromFinancingActivities":{ "type" : "float" },
	"NewLoans":{ "type" : "float" },
	"LoansRepayment":{ "type" : "float" },
	"FixedIncomeDebtInstruments":{ "type" : "float" },
	"RepaymentofFixedIncomeDebtInstruments":{ "type" : "float" },
	"EquityFinancing":{ "type" : "float" },
	"IncreaseDecreaseinCash&CashEquivalents":{ "type" : "float" },
	"Cash&CashEquivalentsatBeginningofYear":{ "type" : "float" },
	"NetCashFlowduetoChangeinExchangeRateOthers":{ "type" : "float" },
	"Cash&CashEquivalentsatEndofYear":{ "type" : "float" },
	"FixedAssets":{ "type" : "float" },
	"Investments":{ "type" : "float" },
	"CurrentAssets":{ "type" : "float" },
	"OtherAssets":{ "type" : "float" },
	"TotalAssets":{ "type" : "float" },
	"LongTermDebt":{ "type" : "float" },
	"OtherLongTermLiabilities":{ "type" : "float" },
	"CurrentLiabilities":{ "type" : "float" },
	"ShareCapital":{ "type" : "float" },
	"Reserves":{ "type" : "float" },
	"Equity":{ "type" : "float" },
	"Inventory":{ "type" : "float" },
	"CashOnHand":{ "type" : "float" },
	"ShortTermDebt":{ "type" : "float" },
	"TotalDebt":{ "type" : "float" },
	"NetProfitMn":{ "type" : "float" },
	"EarningsPerShare":{ "type" : "float" },
	"EPSGrowth":{ "type" : "float" },
	"DividendPerShare":{ "type" : "float" },
	"PEX":{ "type" : "float" },
	"Yield":{ "type" : "float" },
	"NAV":{ "type" : "float" },
	"CurrencyConversion":{ "type" : "float" }
	}
  }
 }
}
'
cd node/info && curl -XPUT 10.0.0.114:9200/_bulk --data-binary @es.json > import.log