#!/bin/sh
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Property_Development
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Airlines
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Services
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Packaged_Foods
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Coal_Mining
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Banks
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Utilities
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Oil_&_Gas_Exploration_&_Production
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Household_Products
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Properties
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Computer_Hardware
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Telecommunications
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Dairy_Products
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Transportation
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Financials
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Footwear
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Hypermarkets__Supermarkets_&_Convenience_Stores
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Insurance
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Electric_Utilities
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Energy
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Marine_Ports_&_Services
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Marine
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Gas_Utilities
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Apparels_&_Accessories
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Software_&_Services
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Property_Investments
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Diversified_Banks
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Textiles__Apparel_&_Luxury_Goods
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Multi-line_Insurance
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Railway_Infrastructure
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Conglomerates
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Casinos_&_Gaming
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Telecommunication_Services
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Food_&_Beverages
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Household_&_Personal_Products
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Consumer_Goods
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Oil_&_Gas
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Other_Diversified_Financial_Services
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Integrated_Oil_&_Gas
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Diversified_Financial_Services
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Retailing
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Properties_&_Construction
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Information_Technology
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Life_&_Health_Insurance
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Property_Conglomerate
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/e-Commerce_&_Internet_Services
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Coal
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/Hotels__Restaurants_&_Leisure
node companyinfo.js http://api-twistedogic01.rhcloud.com/api/sector/IT_Hardware_&_Equipment