library(quantmod)
library(lubridate)
library(TTR)
library(rredis)
# parameters
allStock <- read.csv(file='chronoJob/bluechip',sep='_',header=FALSE)
stockId <- as.vector(allStock$V1)
source('chronoJob/r/ETL.r')
source('chronoJob/r/rsi.r')
source('chronoJob/r/sma.r')